.Dd November 6, 2024
.Dt MDOC-EXAMPLES 7
.Os
.Sh NAME
.Nm mdoc-examples
.Nd print example mdoc source to stdout
.Sh SYNOPSIS
.Nm
.Op Fl v | Fl h
.Sh DESCRIPTION
.Nm
prints some example
.Xr mdoc 7
source to stdout.
The example source is for illustrative purposes only.
.Sh OPTIONS
.Bl -tag -width x
.It Fl v
Print version information to stdout.
.It Fl h
Print usage information to stdout.
.El
.Sh EXIT STATUS
If
.Nm
is able to print the examples, it exits with status code 0.
.Sh SEE ALSO
.Xr mandoc 1 ,
.Xr mdoc 7 ,
.Xr roff 7
.Sh AUTHORS
.An Alexis
